In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Advertising.csv")

In [3]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
X = df.drop('sales',axis=1)
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
poly_convertor=PolynomialFeatures(degree=2,include_bias=False)

In [7]:
Poly_Features=poly_convertor.fit_transform(X)

In [8]:
Poly_Features.shape

(200, 9)

In [9]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(Poly_Features, y, test_size=0.3, random_state=101)

In [56]:
from sklearn.preprocessing import StandardScaler

In [57]:
scaler=StandardScaler()

In [58]:
scaler.fit(X_train)

StandardScaler()

In [59]:
X_train=scaler.transform(X_train)

In [60]:
X_test=scaler.transform(X_test)

In [61]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.59023161,
         0.41659155,  1.6137853 ],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  1.4978238 ,
         2.46478013,  2.08205295],
       [-0.84811893, -1.58789957, -1.02319564, ..., -1.05826214,
        -0.90147492, -0.74882387],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -1.03502374,
        -0.73652035, -0.03590138],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.26199091,
        -0.79680416, -0.78714505],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.32216251,
         0.92114819,  0.76625296]])

In [62]:
X_test

array([[-9.13394717e-01,  1.76259419e+00,  6.81685579e-01,
        -9.63975055e-01,  1.52122095e-02, -2.93048209e-01,
         2.31532893e+00,  1.56001049e+00,  3.69910106e-01],
       [ 1.23121149e+00,  2.36559587e-01, -1.19601922e+00,
         1.38103193e+00,  9.76521639e-01, -6.80562258e-01,
        -5.79325829e-02, -7.40162021e-01, -7.79189389e-01],
       [-4.60024728e-01, -4.07766136e-01,  3.50051150e-01,
        -6.82242743e-01, -5.06457342e-01, -1.10940195e-01,
        -6.39722074e-01, -1.69172158e-01,  3.57554301e-02],
       [-4.96816533e-01,  1.65407618e+00,  9.47927303e-01,
        -7.09383526e-01,  4.86260118e-01,  1.37061544e-01,
         2.10033570e+00,  1.77735495e+00,  6.78908133e-01],
       [-1.42610633e+00,  8.05649381e-02, -1.35015916e+00,
        -1.14433859e+00, -8.66050574e-01, -9.38134722e-01,
        -2.21679679e-01, -8.42466779e-01, -7.93375596e-01],
       [-1.56971305e+00, -5.02719400e-01, -4.11306765e-01,
        -1.16855131e+00, -1.00646472e+00, -8.680574

In [63]:
from sklearn.linear_model import Ridge

In [64]:
ridge_model=Ridge(alpha=100)

In [65]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=100)

In [66]:
y_predcit=ridge_model.predict(X_test)

In [67]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [68]:
mean_absolute_error(y_test,y_predcit)

1.2126062182140163

In [69]:
from sklearn.linear_model import RidgeCV

In [70]:
ridge_cv_model=RidgeCV(alphas=(0.1,0.5,0.7, 1.0, 10.0),scoring="neg_mean_absolute_error")

In [71]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=(0.1, 0.5, 0.7, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [72]:
y_ridge_cv_predict=ridge_cv_model.predict(X_test)

In [73]:
ridge_cv_model.alpha_

1.0

In [74]:
mean_absolute_error(y_test,y_ridge_cv_predict)

0.47968472675005214

In [76]:
from sklearn.linear_model import LassoCV

In [93]:
lasso_cv_model=LassoCV(eps=0.1,n_alphas=100,cv=5)

In [94]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [95]:
y_lassocv_predict=lasso_cv_model.predict(X_test)

In [96]:
mean_absolute_error(y_test,y_lassocv_predict)

0.6541714287492473

In [97]:
mean_squared_error(y_test,y_lassocv_predict)

1.2787267928052637

In [98]:
lasso_cv_model.alpha_

0.4943070909225828

In [99]:
lasso_cv_model.coef_

array([1.00261117, 0.        , 0.        , 0.        , 3.79747867,
       0.        , 0.        , 0.        , 0.        ])

In [100]:
from sklearn.linear_model import ElasticNetCV

In [101]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],tol=0.01)