In [21]:
import numpy as np

## Create numpy array using normal List

In [22]:
normal_list=[1,2,3,4]

In [24]:
 np.array(normal_list)

array([1, 2, 3, 4])

In [25]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [26]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
type(matrix)

list

In [29]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
type(np.array(matrix))

numpy.ndarray

In [31]:
type(np.array(normal_list))

numpy.ndarray

## Create Numpy Array using numpy built in functions 

In [33]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [38]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [44]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [41]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.random.rand(1)

array([0.11488027])

In [46]:
np.random.rand(5)

array([0.31261351, 0.12998046, 0.4791861 , 0.63293423, 0.98718525])

In [47]:
np.random.rand(2,4)

array([[0.46353352, 0.87067065, 0.0715189 , 0.89850734],
       [0.88084982, 0.79281333, 0.95191741, 0.81012445]])

In [48]:
np.random.randn(5)

array([ 0.23742831,  0.17507703,  0.13544038,  0.84982879, -1.24426296])

In [50]:
np.random.randn(3,3)

array([[ 1.81409852,  1.26610061,  0.47317363],
       [-1.81207086, -0.73402142,  1.84894088],
       [ 1.36438294,  0.33506763,  0.03589452]])

In [63]:
np.random.randint(0,4,6)

array([2, 1, 3, 0, 1, 0])

In [67]:
np.random.randint(0,10,(4,3))

array([[7, 4, 5],
       [4, 4, 5],
       [2, 1, 4],
       [8, 8, 8]])

In [70]:
np.random.seed(123)
np.random.randint(0,10,(4,3))

array([[2, 2, 6],
       [1, 3, 9],
       [6, 1, 0],
       [1, 9, 0]])

In [71]:
arr=np.arange(0,12)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
arr.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [74]:
arr.reshape(2,6)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
reshaped_arr=arr.reshape(4,3)

In [77]:
reshaped_arr.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [79]:
reshaped_arr.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [80]:
reshaped_arr.shape

(4, 3)

In [81]:
reshaped_arr.reshape(1,12).shape

(1, 12)

In [82]:
reshaped_arr.max()

11

In [83]:
reshaped_arr.min()

0

In [84]:
reshaped_arr.argmin()

0

In [85]:
reshaped_arr.argmax()

11

In [86]:
reshaped_arr.dtype

dtype('int32')

In [88]:
np.random.rand(4).dtype

dtype('float64')