In [3]:
import numpy as np

In [4]:
arr=np.arange(25)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [11]:
arr=np.arange(11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[0:5]=100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr=np.arange(11)

In [19]:
arr_slice=arr[0:8]

In [20]:
arr_slice[:]=100

In [21]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10])

In [22]:
arr=np.arange(11)

In [23]:
copy_arr=arr.copy()

In [24]:
copy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[:6]=11

In [26]:
arr

array([11, 11, 11, 11, 11, 11,  6,  7,  8,  9, 10])

In [27]:
copy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr_2d=np.array([[3,45,34],[.45,54,46],[22,45,34]])

In [29]:
arr_2d

array([[ 3.  , 45.  , 34.  ],
       [ 0.45, 54.  , 46.  ],
       [22.  , 45.  , 34.  ]])

In [32]:
arr_2d[0]

array([ 3., 45., 34.])

In [33]:
arr_2d[0][1]

45.0

In [34]:
arr_2d[1,2]

46.0

In [41]:
arr_2d_slice=arr_2d[:2,1:]

In [42]:
arr_2d_slice

array([[45., 34.],
       [54., 46.]])

In [43]:
arr=np.arange(11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bol_array=arr>4

In [46]:
bol_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [48]:
arr[bol_array]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr=np.arange(11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
len(arr)

11