In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr1=np.arange(11)

In [8]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr+arr1

ValueError: operands could not be broadcast together with shapes (10,) (11,) 

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr *4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [21]:
arr/0

C:\Users\kavin\AppData\Local\Temp\ipykernel_1836\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0
C:\Users\kavin\AppData\Local\Temp\ipykernel_1836\4291252909.py:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [16]:
0/0

ZeroDivisionError: division by zero

In [22]:
1/arr

C:\Users\kavin\AppData\Local\Temp\ipykernel_1836\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [18]:
0/1

0.0

In [23]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [24]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [25]:
arr.sum()

45

In [26]:
arr.max()

9

In [27]:
arr.mean()

4.5

In [28]:
arr.var()

8.25

In [29]:
arr.std()

2.8722813232690143

In [35]:
arr_2d=np.random.randint(0,45,(5,5))

In [36]:
arr_2d

array([[44,  3, 39, 21, 19],
       [ 8, 22, 10, 28,  6],
       [ 6, 36, 11, 11,  4],
       [ 3,  9, 33,  4, 42],
       [18, 28, 28, 33,  2]])

In [37]:
arr_2d.sum()

468

In [38]:
arr_2d.sum(axis=0)

array([ 79,  98, 121,  97,  73])

In [39]:
arr_2d.sum(axis=1)

array([126,  74,  68,  91, 109])