In [3]:
import numpy as np

In [4]:
my_list=[1,2,3,]

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_list=[[1,2,3],[4,5,6]]

In [8]:
arr=np.array(my_list)

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.arange(0,3)

array([0, 1, 2])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.random.rand(5)

array([0.82331631, 0.61412046, 0.1106333 , 0.52062485, 0.26119975])

In [18]:
np.random.rand(5,3)

array([[0.15844843, 0.81997574, 0.33782956],
       [0.4298609 , 0.19217935, 0.88053013],
       [0.08943862, 0.41399344, 0.70658673],
       [0.72964861, 0.82467806, 0.93451196],
       [0.59013911, 0.4037653 , 0.21212239]])

In [19]:
np.random.randn(5)

array([-0.68918699,  0.95803546, -0.6425679 , -0.21146164,  1.24416769])

In [20]:
np.random.randn(5,3)

array([[-0.52043407,  0.98105296, -0.14620643],
       [-0.75679139,  0.40306119, -0.30741083],
       [ 1.21950644,  0.6938807 ,  0.20291479],
       [ 0.73427028,  0.44705892,  0.37131255],
       [-0.38220889,  0.77625565,  0.29164704]])

In [21]:
np.random.randint(1,100,10)

array([38, 46, 47, 93, 77, 76, 85, 15, 91, 49])

In [24]:
np.random.randint(1,100,10)

array([ 8, 99, 70, 37, 94, 79, 40, 49, 86, 87])

In [27]:
np.random.randint(1,100,(3,4))

array([[ 5, 14, 72, 85],
       [81, 68, 21, 85],
       [25,  4, 95, 31]])

In [30]:
np.random.seed(123)
np.random.randint(1,100,(3,4))

array([[67, 93, 99, 18],
       [84, 58, 87, 98],
       [97, 48, 74, 33]])

In [35]:
arr=np.arange(0,20)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
arr.shape

(20,)

In [38]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
arr.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [40]:
arr.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
arr.max()

97

In [43]:
arr.dtype

dtype('int32')

In [49]:
arr=np.arange(0,10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[8]

8

In [56]:
arr[1:5]=arr[1:5]*2

In [57]:
arr

array([0, 2, 4, 6, 8, 5, 6, 7, 8, 9])

In [58]:
arr=np.random.randint(1,100,(4,5))

In [59]:
arr

array([[47, 97, 26, 84, 79],
       [37, 97, 81, 69, 50],
       [56, 68,  3, 85, 40],
       [67, 85, 48, 62, 49]])

In [63]:
arr[2:,2:]

array([[ 3, 85, 40],
       [48, 62, 49]])

In [66]:
arr=np.arange(0,10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])